version: "3.4"

services:

  nginx:
    image: nginx:1.19
    ports:
      - 80:80
      - 443:443
    networks:
      - nginx_network
    labels:
      - "lt.nephrolog.nginx"
    deploy:
      restart_policy:
        condition: on-failure

networks:
  nginx_network:
    driver: overlay
